# Generated by Django 4.0.3 on 2022-03-10 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msagh_website', '0002_alter_spot_pub_date_alter_spot_title_alter_spot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='title',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
