# Generated by Django 4.0.3 on 2022-03-24 18:33

from django.db import migrations, models
import msagh_website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('msagh_website', '0003_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='admin_aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to='', validators=[msagh_website.validators.validate_size]),
        ),
    ]
