# Generated by Django 4.0.3 on 2022-04-07 16:37

from django.db import migrations, models
import msagh_website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('msagh_website', '0005_alter_meme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to='memes/', validators=[msagh_website.validators.validate_size, msagh_website.validators.validate_shape]),
        ),
    ]
