# Generated by Django 4.0.3 on 2022-04-21 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msagh_website', '0006_alter_meme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msagh_website.spot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
