# Generated by Django 4.0.3 on 2022-04-21 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msagh_website', '0007_comment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_post',
            new_name='CommentSpot',
        ),
    ]
