# Generated by Django 4.0.3 on 2022-04-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msagh_website', '0008_rename_comment_post_commentspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentspot',
            name='title',
        ),
    ]
