# Generated by Django 4.0.3 on 2022-04-27 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msagh_website', '0010_alter_commentspot_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('memes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msagh_website.meme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
