# Generated by Django 4.0.3 on 2022-04-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msagh_website', '0011_commentmeme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmeme',
            old_name='memes',
            new_name='meme',
        ),
    ]
