# Generated by Django 4.0.3 on 2022-05-27 17:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_bio_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_url',
            field=models.URLField(blank=True, default='Brak informacji'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='Brak informacji', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, default='Brak informacji'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='Brak informacji', max_length=16),
        ),
    ]
