# Generated by Django 4.0.3 on 2022-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile_contact_url_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_url',
            field=models.CharField(blank=True, default='Brak informacji', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, default='Brak informacji', max_length=200),
        ),
    ]
