# Generated by Django 4.0.3 on 2022-05-27 18:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profile_contact_url_alter_profile_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Brak informacji', max_length=2),
        ),
    ]
