# Generated by Django 4.0.3 on 2022-05-28 10:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='Brak informacji', max_length=2),
        ),
    ]
